name: CI/CD to AWS EC2 Instance with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      # Debug folder structure (optional but helpful)
      - name: Debug folder structure
        run: |
          pwd
          ls -R

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend-springbootapp
          # CORRECTED PATH: Points to the Dockerfile inside the backend folder
          file: ./backend-springbootapp/backend.dockerfile
          push: true
          tags: 2300033639/dockeraws-backend:latest

      
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend-reactapp
          # CORRECTED PATH: Points to the Dockerfile inside the frontend folder
          file: ./frontend-reactapp/frontend.dockerfile
          push: true
          tags: 2300033639/dockeraws-frontend:latest

      # Save the EC2 private key to a file
      - name: Save EC2 private key
        run: |
          echo "${{ secrets.AWS_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      # Install Docker Compose (if not already installed on EC2)
      - name: Install Docker Compose on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.AWS_IP }} << 'EOF'
            # Ensure Docker is installed first
            if ! command -v docker &> /dev/null; then
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            # Install Docker Compose
            if ! command -v docker-compose &> /dev/null; then
              curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              docker-compose --version
            fi
          EOF

      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.AWS_IP }} << 'EOF'
            # Navigate to project folder or clone if it doesn't exist
            if [ -d "DEVOPS-EXAM-2300033639" ]; then
              cd DEVOPS-EXAM-2300033639
              git pull origin main
            else
              git clone https://github.com/${{ github.repository }}.git DEVOPS-EXAM-2300033639
              cd DEVOPS-EXAM-2300033639
            fi

            # Check for docker-compose.yml
            if [ ! -f "docker-compose.yml" ]; then
              echo "docker-compose.yml not found!"
              exit 1
            fi

            # Redeploy
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d --build
          EOF
